import type { Metadata } from "next";

import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/site.css";
import "../styles/fontawesome/css/all.css";
import "../styles/roboto/roboto.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body className="min-vh-100 d-flex flex-column">{children}</body>
    </html>
  );
}
